spring:
  messages:
    basename: i18n/messages
  thymeleaf:
    mode: HTML
    cache: false

mybatis:
  configuration:
    useColumnLabel: true
    mapUnderscoreToCamelCase: true
  mapper-locations: mybatis/sql/*.xml
